name = "alicesaidhi/conch"
version = "0.1.0"
description = "Modern command library for Roblox"
authors = ["alicesaidhi"]
repository = "https://github.com/alicesaidhi/conch"
license = "MIT"
private = true

workspace_members = ["pkgs/*", "example"]

[target]
environment = "roblox"

[engines]
pesde = "^0.7.2"
lune = "^0.10.2"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts_rojo/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts_rojo/sourcemap_generator.luau"

[dev_dependencies]
scripts_rojo = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.6.1", target = "lune" }
