# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
pesde = "daimond113/pesde@0.6.2+registry.0.2.2"
rojo = "rojo-rbx/rojo@7.4.4"
lune = "lune-org/lune@0.10.4"
wally = "UpliftGames/wally@0.3.2"
StyLua = "johnnymorganz/stylua@2.3.1"
zap = "red-blox/zap@0.6.24"
